version: '2'
services:
  web:
    build: .
    depends_on:
      - redis
    environment:
      NODE_ENV: 'development'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      VIRTUAL_HOST: mathman.docker
    labels:
      - "traefik.enable=true"
    networks:
      default:
        aliases:
          - mathman-web.inseng.test
          - mathman-web
  redis:
    image: 'redis:3'
networks:
  default:
    external: true
    name: "inst_shared"